server:
  port: 8082

spring:
  profiles:
    active: h2
  datasource:
    url: jdbc:h2:file:~/db/hairstyle
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
      hibernate:
        ddl-auto: update